---

env:
  browser: true
  es6: true

parser: '@typescript-eslint/parser'

parserOptions:
  project:
    - tsconfig.lint.json
  sourceType: module

extends:
  - '@matthiaskunnen/eslint-config-angular'

overrides:
  -
    parserOptions:
      project:
        - build/tsconfig.json
    files:
      - 'build/**/*.ts'
    env:
      browser: false
      node: true

  -
    files:
      - 'src/**/*.interface.ts'
      - 'src/**/*.model.ts'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig.lint.json
      sourceType: module

    rules:
      '@typescript-eslint/member-ordering':
        - error
        -
          default:
            memberTypes:
              - public-static-field
              - protected-static-field
              - private-static-field
              - public-instance-field
              - protected-instance-field
              - private-instance-field
              - public-constructor
              - protected-constructor
              - private-constructor
              - public-static-method
              - protected-static-method
              - private-static-method
              - public-instance-method
              - protected-instance-method
              - private-instance-method
              - signature
            order: alphabetically


rules:
  no-console: error
