---

env:
  es6: true

overrides:
  -
    files:
      - '*.js'
    env:
      node: true
    extends:
      - '@matthiaskunnen/eslint-config-base'

  -
    files:
      - 'api/**/*.ts'
    env:
      node: true
    extends:
      - '@matthiaskunnen/eslint-config-typescript-node'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - tsconfig.lint.json
      sourceType: module
    rules:
      '@typescript-eslint/no-base-to-string': off
      '@typescript-eslint/no-invalid-void-type': off
      '@typescript-eslint/require-await': off
      no-console: off

  -
    files:
      - 'build/**/*.ts'
    env:
      node: true
    extends:
      - '@matthiaskunnen/eslint-config-typescript-node'
    parserOptions:
      project:
        - build/tsconfig.json
    rules:
      '@typescript-eslint/no-unused-vars': off
      '@typescript-eslint/no-var-requires': off

  -
    files:
      - 'shared/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - tsconfig.lint.json
      sourceType: module
    rules:
      no-console: off
      no-param-reassign: off

  -
    files:
      - 'src/**/*.ts'
    env:
      browser: true
    extends:
      - '@matthiaskunnen/eslint-config-angular'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project:
        - tsconfig.lint.json
      sourceType: module
    rules:
      '@typescript-eslint/no-invalid-void-type': off
      '@typescript-eslint/no-redundant-type-constituents': off
      no-console: error
      no-param-reassign: off

  -
    files:
      - 'src/**/*.interface.ts'
      - 'src/**/*.model.ts'
    rules:
      '@typescript-eslint/member-ordering':
        - error
        -
          default:
            memberTypes:
              - public-static-field
              - protected-static-field
              - private-static-field
              - public-instance-field
              - protected-instance-field
              - private-instance-field
              - public-constructor
              - protected-constructor
              - private-constructor
              - public-static-method
              - protected-static-method
              - private-static-method
              - public-instance-method
              - protected-instance-method
              - private-instance-method
              - signature
            order: alphabetically
  -
    files:
      - '*.html'
    extends:
      - '@matthiaskunnen/eslint-config-angular/templates.js'
    rules:
      '@angular-eslint/template/button-has-type': off
      '@angular-eslint/template/label-has-associated-control': off
