plugins:
  - stylelint-order
rules:
  at-rule-empty-line-before:
    - always
    -
      except:
        - blockless-after-same-name-blockless
      ignore:
        - after-comment
      ignoreAtRules:
        - include
  at-rule-name-case: lower
  at-rule-name-newline-after: always-multi-line
  at-rule-name-space-after: always-single-line
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-before: always-single-line
  block-no-empty: true
  block-opening-brace-newline-after: always
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  color-hex-case: lower
  color-hex-length: short
  color-named: always-where-possible
  comment-empty-line-before:
    - always
    -
      except:
        - first-nested
      ignore:
        - stylelint-commands
  comment-no-empty: true
  comment-whitespace-inside: always
  custom-property-empty-line-before:
    - always
    -
      except:
        - after-custom-property
        - first-nested
      ignore:
        - after-comment
        - inside-single-line-block
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always-single-line
  declaration-colon-space-before: never
  declaration-empty-line-before: null
  font-family-name-quotes: always-where-recommended
  font-weight-notation: named-where-possible
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: always-multi-line
  function-comma-space-after: always-single-line
  function-comma-space-before: never
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-parentheses-space-inside: never-single-line
  function-url-quotes: never
  function-whitespace-after: always
  indentation: 4
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  max-empty-lines: 1
  max-line-length: 100
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-name-value-allowed-list:
    min-width:
      - 360px
      - 400px
      - 480px
      - 600px
      - 720px
      - 840px
      - 960px
      - 1024px
      - 1280px
      - 1440px
      - 1600px
      - 1920px
    max-width:
      - 359px
      - 399px
      - 479px
      - 599px
      - 719px
      - 839px
      - 959px
      - 1023px
      - 1279px
      - 1439px
      - 1599px
      - 1919px
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-space-after: always-single-line
  media-query-list-comma-space-before: never
  no-duplicate-selectors: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-missing-end-of-source-newline: true
  number-leading-zero: always
  number-no-trailing-zeros: true
  order/properties-order:
    - display
    - position
    - top
    - right
    - bottom
    - left

    - flex
    - flex-basis
    - flex-direction
    - flex-flow
    - flex-grow
    - flex-shrink
    - flex-wrap
    - align-content
    - align-items
    - align-self
    - justify-content
    - order

    - box-sizing

    - width
    - min-width
    - max-width

    - height
    - min-height
    - max-height

    - margin
    - margin-top
    - margin-right
    - margin-bottom
    - margin-left

    - padding
    - padding-top
    - padding-right
    - padding-bottom
    - padding-left

    - float
    - clear

    - resize

    - columns
    - column-count
    - column-gap
    - column-fill
    - column-rule
    - column-span
    - column-width

    - grid-gap
    - grid-template-columns

    - animation
    - animation-name
    - animation-timing-function

    - transform
    - transform-box
    - transform-origin
    - transform-style

    - transition
    - transition-delay
    - transition-duration
    - transition-property
    - transition-timing-function

    # Border

    - border
    - border-top
    - border-right
    - border-bottom
    - border-left
    - border-width
    - border-top-width
    - border-right-width
    - border-bottom-width
    - border-left-width

    - border-style
    - border-top-style
    - border-right-style
    - border-bottom-style
    - border-left-style

    - border-radius
    - border-top-left-radius
    - border-top-right-radius
    - border-bottom-left-radius
    - border-bottom-right-radius

    - border-color
    - border-top-color
    - border-right-color
    - border-bottom-color
    - border-left-color

    - outline
    - outline-color
    - outline-offset
    - outline-style
    - outline-width

    # Background

    - background
    - background-attachment
    - background-clip
    - background-color
    - background-image
    - background-repeat
    - background-position
    - background-size

    - fill

    - opacity

    # Text

    - color

    - font
    - font-family
    - font-size
    - font-smoothing
    - font-style
    - font-variant
    - font-weight

    - letter-spacing
    - line-height
    - list-style

    - text-align
    - text-decoration
    - text-indent
    - text-overflow
    - text-rendering
    - text-shadow
    - text-transform
    - text-wrap

    - white-space
    - word-spacing

    # Cursor

    - cursor
    - pointer-events
    - user-select

    # Other

    - appearance
    - border-collapse
    - border-spacing
    - box-shadow
    - caption-side
    - content
    - empty-cells
    - overflow
    - overflow-x
    - overflow-y
    - quotes
    - speak
    - table-layout
    - vertical-align
    - visibility
    - will-change
    - z-index
  property-case: lower
  property-no-vendor-prefix:
    - true
    -
      ignoreProperties:
        - appearance
  rule-empty-line-before:
    - always-multi-line
    -
      ignore:
        - after-comment
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-class-pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-id-pattern: '^[a-z0-9]+(-[a-z0-9]+)*$'
  selector-list-comma-newline-after: always-multi-line
  selector-list-comma-space-before: never
  selector-max-empty-lines: 0
  selector-no-vendor-prefix: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: single
  unit-case: lower
  value-keyword-case: lower
  value-list-comma-newline-after: always-multi-line
  value-list-comma-space-after: always-single-line
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true
