/* eslint-disable */

// This file is automatically generated by generate-environment.ts using yarn run build:env:pre. It
// is used to inject the release into the production environment. It is recommended to ignore this
// file using git update-index --skip-worktree src/environments/environment.generated.ts
export const generatedEnvironment = {
    "release": undefined
};
